# Generated by Django 5.0.1 on 2024-01-31 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(unique=True)),
                ('ename', models.CharField(max_length=20)),
                ('esal', models.FloatField()),
                ('eaddr', models.CharField(max_length=120)),
            ],
        ),
    ]
